### ISSUE TITLE
outputting black image

### ISSUE THREAD

**Issue by sneccc** [bvhari/ComfyUI_PerpNeg#1]
Hello i just tried the node and its just outputting  a black image:
![image](https://github.com/bvhari/ComfyUI_PerpNeg/assets/61990796/8627d1dc-ae57-430e-8db4-06da550edbf4)
do you have any idea why this happens?

**Comment by bvhari** [comment]
The issue is due to changes in Comfy.
ComfyUI now has Perp-Neg, so you can use that version instead.
