### ISSUE TITLE
recent comfyui changes break execution

### ISSUE THREAD

**Issue by bitjockeypro** [bvhari/ComfyUI_PerpNeg#2]
Thanks for the sampler, I use it all the time.

A recent change in comfyui seems to have broken the sampler:

`Error occurred when executing KSamplerAdvancedPerpNeg:

'KSampler' object has no attribute 'model_wrap'

File "H:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "H:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "H:\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_PerpNeg\perpneg.py", line 638, in sample
return ksampler_perpneg(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, nocond, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise, extra_options_perpneg=extra_options_perpneg)
File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_PerpNeg\perpneg.py", line 582, in ksampler_perpneg
samples = sample_perpneg(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, nocond, latent_image,
File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_PerpNeg\perpneg.py", line 530, in sample_perpneg
positive_nocond_copy, negative_nocond_copy = process_conds_comfy(
File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_PerpNeg\perpneg.py", line 111, in process_conds_comfy
calculate_start_end_timesteps(self.model_wrap, negative)`

**Comment by bitjockeypro** [comment]
I temporarily implemented a workaround by resetting to a previous commit for comfyui:
`git reset aeba1cc2a068ba66b2701bf2aaba21a6364337bf --hard`

**Comment by bitjockeypro** [comment]
Upgrading comfyui, and hard resetting comfyui_perpneg to commit 779abe4495bb2e92ef516d2745c4ad1a5b3653af also fixes the issue - btw I'm using SD-1.5 - so it seems the problem was introduced with this commit:

commit aa6463211bfc8b4b9026a4351355d4ad98860696
Author: BVH <82035780+bvhari@users.noreply.github.com>
Date:   Fri Sep 1 21:11:58 2023 +0530

    Fix issues with SDXL

**Comment by lstyls** [comment]
Yep this is still borked downloaded this node to try out today and getting the same error. It's not immediately obvious from the commit history where the dependency broke, otherwise I would submit a PR. @bvhari FYI this project is broken

**Comment by bvhari** [comment]
ComfyUI has Perp-Neg now, so this node is redundant.
Please use the ComfyUI version.
